"""Daily report builder. Always writes fallback markdown; optionally pushes to Slack."""
import json
import time
from pathlib import Path
from urllib import request, error


def build_report(state_dir, targets):
    cur = Path(state_dir) / "current.json"
    data = {}
    if cur.exists():
        try:
            data = json.loads(cur.read_text())
        except json.JSONDecodeError:
            pass

    cts = data.get("cts", {})
    done = [c for c in cts.values() if c.get("status") == "done"]
    rollbacks = [c for c in cts.values() if c.get("status") == "done_with_rollback"]
    regressed = [c for c in cts.values() if c.get("status") == "regressed"]
    aborted = [c for c in cts.values() if c.get("status") == "aborted"]
    in_flight = [c for c in cts.values() if c.get("status") in ("pending", "in_progress")]
    halted = data.get("halted", False)

    # Cross-reference targets for per-CT snap_strategy. Used to tag CTs that
    # ran (or failed) on the fix-forward path so the report flags the absence
    # of snapshot protection unambiguously.
    target_by_ctid = {c["ctid"]: c for c in targets.get("cts", []) or []}

    def _name_strategy(ct):
        t = target_by_ctid.get(int(ct["ctid"]), {})
        return t.get("name", "?"), t.get("snap_strategy", "?")

    fix_forward_done = [
        c for c in done
        if target_by_ctid.get(int(c["ctid"]), {}).get("snap_strategy") == "fix-forward-enhanced"
    ]

    lines = []
    lines.append(f"# PatchWave daily report — {time.strftime('%Y-%m-%d')}")
    lines.append("")
    lines.append(f"**Run ID:** {data.get('run_id', '(no run)')}  ")
    lines.append(f"**Started:** {data.get('started', '-')}  ")
    lines.append(f"**Halted:** {halted}  ")
    if halted:
        lines.append(f"**Halt reason:** {data.get('halt_reason','-')} at {data.get('halted_at','-')}")
    lines.append("")
    lines.append(f"## Counts")
    lines.append(f"- Done OK: {len(done)} (of which {len(fix_forward_done)} WITHOUT snapshot protection)")
    lines.append(f"- Done with rollback: {len(rollbacks)}")
    lines.append(f"- Regressed (fix-forward, no rollback): {len(regressed)}")
    lines.append(f"- Aborted: {len(aborted)}")
    lines.append(f"- In flight / pending: {len(in_flight)}")
    lines.append("")
    if fix_forward_done:
        lines.append("## Patched WITHOUT snapshot protection (fix-forward-enhanced)")
        lines.append("These CTs were patched in place; no `pct snapshot` rollback exists. "
                     "Pre-patch baselines are recorded in the run's state directory; old debs "
                     "retained in `/var/cache/apt/archives/` for manual downgrade.")
        for c in fix_forward_done:
            name, _ = _name_strategy(c)
            lines.append(f"- ct{c['ctid']} {name}")
        lines.append("")
    if regressed:
        lines.append("## REGRESSED — fix-forward post-probe failure (no rollback)")
        lines.append("Patched, but app post-probe failed. CT left running for inspection. "
                     "Manual recovery required (downgrade via retained debs or hand-fix).")
        for c in regressed:
            name, _ = _name_strategy(c)
            pp = c.get("steps", {}).get("post_probe", {}).get("detail", "-")
            lines.append(f"- ct{c['ctid']} {name}: {pp}")
        lines.append("")
    if rollbacks:
        lines.append("## Rollbacks — operator review")
        for c in rollbacks:
            lines.append(f"- ct{c['ctid']}: {c.get('steps',{}).get('post_probe',{}).get('detail','-')}")
        lines.append("")
    if aborted:
        lines.append("## Aborts")
        for c in aborted:
            failed_step = next(
                (s for s, info in c.get("steps", {}).items() if info.get("status") == "fail"),
                "?")
            detail = c.get("steps", {}).get(failed_step, {}).get("detail", "-")
            lines.append(f"- ct{c['ctid']} at step `{failed_step}`: {detail}")
        lines.append("")

    # Pending approval-gated CTs (Tier 3 + never-auto)
    policy = targets.get("policy", {}) or {}
    gated = set(policy.get("approval_gated_tier3", []) or [])
    never_auto = set(policy.get("never_auto", []) or [])
    lines.append("## Approval-gated backlog (Tier 3)")
    for c in targets.get("cts", []):
        if c["ctid"] in gated:
            tag = " [NEVER-AUTO]" if c["ctid"] in never_auto else ""
            stay = " [STAY-STOPPED]" if c.get("stay_stopped") else ""
            lines.append(f"- ct{c['ctid']} {c['name']}{tag}{stay}")
    lines.append("")
    lines.append("---")
    lines.append("Generated by PatchWave reporter.")
    return "\n".join(lines)


def post_to_slack(report_text, webhook_url):
    """Optional Slack push. Non-blocking — failure returns (False, reason) and caller continues."""
    if not webhook_url:
        return None, "slack webhook not configured (skipped)"
    payload = json.dumps({"text": report_text}).encode("utf-8")
    req = request.Request(webhook_url, data=payload, method="POST")
    req.add_header("Content-Type", "application/json")
    try:
        with request.urlopen(req, timeout=15) as r:
            return (200 <= r.status < 300), f"http {r.status}"
    except (error.URLError, TimeoutError) as e:
        return False, f"slack post failed: {e}"


def write_fallback(report_text, log_dir):
    p = Path(log_dir) / f"report-{time.strftime('%Y%m%d')}.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(report_text)
    return p
